MultiError now defines its ``exceptions`` attribute in ``__init__()``
to better support linters and code autocompletion.
